### ISSUE TITLE
Сообщества ruhaskell на реддите больше нет

### ISSUE THREAD

**Issue by ShrykeWindgrace** [ruHaskell/ruhaskell#121]
https://www.reddit.com/r/ruhaskell/ - Sorry, there aren’t any communities on Reddit with that name.

А ссылка на него на ruhaskell.org всё ещё есть =)

**Comment by dpwiz** [comment]
Гиттера тоже, наверно?

**Comment by ShrykeWindgrace** [comment]
@dpwiz Удивительно, но гиттер ещё трепыхается.
