### ISSUE TITLE
Предложение - перенос статей из архива форума it-talk.org

### ISSUE THREAD

**Issue by afiskon** [ruHaskell/ruhaskell#14]
Как вам может быть известно, в прошлом году я закрыл свой форум http://afiskon.ru/it-talk.html Для тех, кто переходит на него с Google, был опубликован архив форума, кроме того, почти полный архив есть на web.archive.org

Так вот, в разделе "Читальный зал" был десяток, а то и пара десятков неплохих статей о Haskell, как авторских, так и переводных. Есть предложение перенести их на ruhaskell.org.

**Comment by denisshevchenko** [comment]
Прекрасное предложение! Да, статей и вправду много. Они определённо должны быть перенесены на ruhaskell.org.

**Comment by wiz** [comment]
Меня посещала такая идея, но я что-то подзабил. Надо бы парочку своих статеек всё же переложить, раз это одобряется.

**Comment by denisshevchenko** [comment]
> Надо бы парочку своих статеек всё же переложить, раз это одобряется.

Не просто одобряется, а всячески приветствуется!

**Comment by qnikst** [comment]
UP! кто этим делом заниматься собирается, если да, то можно было бы назначиться в `assignee`, если нет, то хорошо бы список статей которые интересны, т.к. я например не знаю где там искать.

**Comment by denisshevchenko** [comment]
Читать вот здесь: http://web.archive.org/web/20141018141308/http://it-talk.org/forum23.html. Там 12 страниц, но если фильтровать по слову "Haskell", то статей не так уж и много. Из них есть кое-что любопытное.
