### ISSUE TITLE
Полезные ссылки

### ISSUE THREAD

**Issue by alogic0** [ruHaskell/ruhaskell#92]
В [Links.hs](https://github.com/ruHaskell/ruhaskell/blob/master/src/Markup/Links.hs) сказано:  
"не спрашивайте почему".
    Может лучше:   
"альтернативный сайт тех, кто считает, что всё нужно делать через Stack" ?

**Comment by wiz** [comment]
А в чём, кстати, официальность первого?

**Comment by wiz** [comment]
Они оба весьма "официальные". Только один от конторы welltyped, а другой от конторы fpcomplete.

**Comment by cblp** [comment]
Там ещё где-то есть ~~Неизвестные Отцы~~ комитет.

**Comment by qnikst** [comment]
Сайта Haskell-lang.org больше нет, теперь он ведёт на https://tech.fpcomplete.com/haskell есть мнение, что теперь даже формулировка "альтернативный" не подходит. С другой стороны раздела для блогов коммерческих компаний и интересных сайтов у нас нет, и похоже стоит завести.

**Comment by cblp** [comment]
Какие изменения предлагается внести? Можно в виде патча.

**Comment by cblp** [comment]
done
