### ISSUE TITLE
Bump year

### ISSUE THREAD

**Issue by sobolevn** [ruHaskell/ruhaskell#95]
I have noticed that year in the footer is not up-to-date.
<img width="673" alt="2018-03-20 17 58 10" src="https://user-images.githubusercontent.com/4660275/37662544-5a0be32e-2c68-11e8-9be5-ef7218ae7b3e.png">

**Comment by cblp** [comment]
Действительно. Может, вы хотите внести исправление?

**Comment by sobolevn** [comment]
Нет, я не хочу.

**Comment by cblp** [comment]
done
